// ============================================================
// P08 — Mini-Project: Task Manager
// File: lib/features/tasks/models/task.dart
//
// Immutable Task model using Freezed.
// Slide reference: P05 "Freezed — Immutable Union Types"
// Key quote: "Freezed gives you copyWith, == operator,
//             toString and hashCode — all generated."
//
// HOW TO REGENERATE:
//   dart run build_runner build --delete-conflicting-outputs
//
// This creates task.freezed.dart and task.g.dart alongside this file.
// ============================================================

import 'package:freezed_annotation/freezed_annotation.dart';

// These two lines are required for Freezed code generation.
// They reference the generated files.
part 'task.freezed.dart';
part 'task.g.dart';

// Task priority enum — type-safe, no magic strings
enum TaskPriority {
  low,
  medium,
  high;

  String get label => switch (this) {
        TaskPriority.low => 'Low',
        TaskPriority.medium => 'Medium',
        TaskPriority.high => 'High',
      };
}

// Task category
enum TaskCategory {
  personal,
  work,
  study,
  health,
  other;

  String get label => switch (this) {
        TaskCategory.personal => 'Personal',
        TaskCategory.work => 'Work',
        TaskCategory.study => 'Study',
        TaskCategory.health => 'Health',
        TaskCategory.other => 'Other',
      };
}

// ============================================================
// @freezed class — Freezed generates:
//   ✓ const constructor
//   ✓ copyWith() — create new instance with changed fields
//   ✓ == and hashCode — value equality
//   ✓ toString() — readable debug output
//   ✓ fromJson / toJson (with @JsonSerializable)
// ============================================================
@freezed
class Task with _$Task {
  const factory Task({
    required String id,
    required String title,
    @Default('') String description,
    @Default(false) bool isCompleted,
    @Default(TaskPriority.medium) TaskPriority priority,
    @Default(TaskCategory.personal) TaskCategory category,
    required DateTime createdAt,
    DateTime? dueDate,
    String? userId, // owner — for Firestore security rules
  }) = _Task;

  // fromJson — generated by json_serializable (in task.g.dart)
  factory Task.fromJson(Map<String, dynamic> json) => _$TaskFromJson(json);
}

// ============================================================
// MANUAL MODEL VERSION
// If you're not using Freezed yet, here's the equivalent
// hand-written class. Students should understand this first.
// ============================================================

// class Task {
//   final String id;
//   final String title;
//   final String description;
//   final bool isCompleted;
//   final TaskPriority priority;
//   final DateTime createdAt;
//   final DateTime? dueDate;
//
//   const Task({
//     required this.id,
//     required this.title,
//     this.description = '',
//     this.isCompleted = false,
//     this.priority = TaskPriority.medium,
//     required this.createdAt,
//     this.dueDate,
//   });
//
//   // copyWith — creates a new Task with some fields changed
//   Task copyWith({
//     String? id,
//     String? title,
//     String? description,
//     bool? isCompleted,
//     TaskPriority? priority,
//     DateTime? createdAt,
//     DateTime? dueDate,
//   }) {
//     return Task(
//       id: id ?? this.id,
//       title: title ?? this.title,
//       description: description ?? this.description,
//       isCompleted: isCompleted ?? this.isCompleted,
//       priority: priority ?? this.priority,
//       createdAt: createdAt ?? this.createdAt,
//       dueDate: dueDate ?? this.dueDate,
//     );
//   }
//
//   // toJson — for Firestore / SharedPreferences
//   Map<String, dynamic> toJson() => {
//     'id': id,
//     'title': title,
//     'description': description,
//     'isCompleted': isCompleted,
//     'priority': priority.name,
//     'createdAt': createdAt.toIso8601String(),
//     'dueDate': dueDate?.toIso8601String(),
//   };
//
//   factory Task.fromJson(Map<String, dynamic> json) => Task(
//     id: json['id'],
//     title: json['title'],
//     description: json['description'] ?? '',
//     isCompleted: json['isCompleted'] ?? false,
//     priority: TaskPriority.values.firstWhere((p) => p.name == json['priority']),
//     createdAt: DateTime.parse(json['createdAt']),
//     dueDate: json['dueDate'] != null ? DateTime.parse(json['dueDate']) : null,
//   );
//
//   @override
//   bool operator ==(Object other) =>
//       identical(this, other) || other is Task && other.id == id;
//
//   @override
//   int get hashCode => id.hashCode;
//
//   @override
//   String toString() => 'Task(id: $id, title: $title, done: $isCompleted)';
// }
